/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef} from 'react'
import { useGLTF} from '@react-three/drei'

export default function Model(props) {

  const group = useRef()
  const { nodes, materials } = useGLTF('/Bucket.glb')

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.polySurface17_lambert2_0.geometry} material={nodes.polySurface17_lambert2_0.material} />
          <mesh geometry={nodes.polySurface17_phongE1_0.geometry} material={nodes.polySurface17_phongE1_0.material} />
          <mesh geometry={nodes.polySurface18_phongE1_0.geometry} material={nodes.polySurface18_phongE1_0.material} />
          <mesh geometry={nodes.polySurface19_phongE1_0.geometry} material={nodes.polySurface19_phongE1_0.material} />
          <mesh geometry={nodes.polySurface1_lambert2_0.geometry} material={nodes.polySurface1_lambert2_0.material} />
        </group>
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/Bucket.glb')
