/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF,  } from '@react-three/drei'
import { useCylinder } from '@react-three/cannon'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { useLoader } from '@react-three/fiber'

export default function Coin(props) {
  const group = useRef()
  const [ref] = useCylinder(() => ({mass: 1, rotation: [Math.PI * Math.random(), 0, 0], position: [...props.position], args: [0.4, 0.4, 0.15]}))

  const { nodes, materials} = useLoader(GLTFLoader, '/trueCoin.glb')
  
  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]} scale={0.004}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group name="little-gcoin" position={[1.24, 0, -3.54]} rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
            <group position={[0, 5.91, 0]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes['little-gcoin__0'].geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/trueCoin.glb')
